### ISSUE TITLE
Breaks scout movement.

### ISSUE THREAD

**Issue by douglasb78** [mphe/TF2-ClassicMovement#1]
After installing Classic Movement Scout isn't able to double-jump anymore and it has an exaggerated strafe speed. There should be an option to disable Classic Movemnt for scout.

**Comment by mphe** [comment]
Works fine for me.
I'm about 99% sure it's a problem with your setup not with the plugin, as CM has nothing to do with jumping, other than checking if you hold down jump and just touched the ground for autohopping.

What do you mean with exaggerated strafe speed?
Do you have other plugins installed that somehow modify player movement?
Are you using autohop or scroll wheel to jump?
If you're using scrollwheel, there's your problem. If you spam jump inputs Scout will double jump immediately of course. This is normal game behavior that you would face without this plugin, too.

An option to disable the plugin for Scout would make no sense, because it only affects the movement speed and nothing else.

**Comment by douglasb78** [comment]
Yes, it's my fault. I was testing the plugin using a script that automatically presses space bar every 20ms, then I noticed the plugin has an auto-bhop feature.
